"""
Django production settings for core project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from .base import *
from dotenv import load_dotenv


load_dotenv()

print("Run production server configuration")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
print(f'{DEBUG=}', DEBUG)


SECRET_KEY = os.environ.get('SECRET_KEY', 'secret-key-r9crzp6^5+du%95n=p$-)=u-apaemk3w(5n=p$-)=u-apaemk3w(o4c%6&z')
print(f'Production {SECRET_KEY=}')

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME":   os.path.join(BASE_DIR, "db.sqlite3"),
    }
}